# Generated by Django 3.0.8 on 2020-07-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='freq',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lines',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lines',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lines',
            name='status',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
