# Generated by Django 3.0.8 on 2020-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200731_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='freq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
